"""Add location fields to Sensor model

Revision ID: 6def08de80a3
Revises: 9b9d83df0200
Create Date: 2022-11-25 17:30:45.381944

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '6def08de80a3'
down_revision = '9b9d83df0200'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('sensor', sa.Column('lon', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor', 'lon')
    op.drop_column('sensor', 'lat')
    # ### end Alembic commands ###
