"""Create temperature table

Revision ID: 850699ff3c74
Revises: cee06d557493
Create Date: 2022-11-21 19:32:03.382653

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '850699ff3c74'
down_revision = 'cee06d557493'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temperatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('sensor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temperatures_sensor_id'), 'temperatures', ['sensor_id'], unique=False)
    op.create_index(op.f('ix_temperatures_timestamp'), 'temperatures', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_temperatures_timestamp'), table_name='temperatures')
    op.drop_index(op.f('ix_temperatures_sensor_id'), table_name='temperatures')
    op.drop_table('temperatures')
    # ### end Alembic commands ###
