"""Add humidity to temperature model

Revision ID: 91084f7da5a5
Revises: 6def08de80a3
Create Date: 2022-12-01 03:46:14.842825

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '91084f7da5a5'
down_revision = '6def08de80a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temperature', sa.Column('humidity', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temperature', 'humidity')
    # ### end Alembic commands ###
