"""empty message

Revision ID: 9b9d83df0200
Revises: 
Create Date: 2022-11-22 19:51:12.422299

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '9b9d83df0200'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mac_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('sensor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_mac_address'), 'device', ['mac_address'], unique=False)
    op.create_index(op.f('ix_device_sensor_id'), 'device', ['sensor_id'], unique=False)
    op.create_index(op.f('ix_device_timestamp'), 'device', ['timestamp'], unique=False)
    op.create_table('temperature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('sensor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temperature_sensor_id'), 'temperature', ['sensor_id'], unique=False)
    op.create_index(op.f('ix_temperature_timestamp'), 'temperature', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_temperature_timestamp'), table_name='temperature')
    op.drop_index(op.f('ix_temperature_sensor_id'), table_name='temperature')
    op.drop_table('temperature')
    op.drop_index(op.f('ix_device_timestamp'), table_name='device')
    op.drop_index(op.f('ix_device_sensor_id'), table_name='device')
    op.drop_index(op.f('ix_device_mac_address'), table_name='device')
    op.drop_table('device')
    op.drop_table('sensor')
    # ### end Alembic commands ###
