"""empty message

Revision ID: aba36ba80508
Revises: 
Create Date: 2022-11-20 20:26:46.859006

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'aba36ba80508'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mac_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('sensor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_sensor_id'), 'devices', ['sensor_id'], unique=False)
    op.create_index(op.f('ix_devices_timestamp'), 'devices', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_timestamp'), table_name='devices')
    op.drop_index(op.f('ix_devices_sensor_id'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
