"""Add index to mac_address

Revision ID: cee06d557493
Revises: aba36ba80508
Create Date: 2022-11-20 20:42:26.611716

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cee06d557493'
down_revision = 'aba36ba80508'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('devices', 'mac_address',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_devices_mac_address'), 'devices', ['mac_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_mac_address'), table_name='devices')
    op.alter_column('devices', 'mac_address',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
